#!/bin/bash

dir=$PWD
cd ~/code/my_stl/cpp/build/ninja
cmake -GNinja ../..
if (( $? != 0 )); then
    echo "Error with CMake"
    cd $dir
    return 1
fi

ninja
if (( $? != 0 )); then
    echo "Error with ninja"
    cd $dir
    return 2
fi

./unit_tests
cd $dir
